language: minimal

services:
  - docker

cache:
  directories:
    "./cache"

jobs:
  include:
    - install:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      script:
        - minecraft/build.sh
