language: shell

services:
  - docker

cache:
  directories:
    "./cache"

jobs:
  include:
    - &docker-build
      stage: Build
      install:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
        - docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
      script: minecraft/build.sh
      after_script: utils/push.sh
    - <<: *docker-build
      script: docker build cassandra/jenkins -t $BUILD_ROOT/cassandra-jenkins:latest
    - <<: *docker-build
      script: docker build pleroma -t $BUILD_ROOT/pleroma:latest || true
    - <<: *docker-build
      script: docker build prosody -t $BUILD_ROOT/prosody:latest
