language: shell

services:
  - docker

cache:
  directories:
    "./cache"

jobs:
  include:
    - &docker-build
      stage: Build
      install: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      script: minecraft/build.sh
      after_script: utils/push.sh
    - <<: *docker-build
      script: docker build cassandra/jenkins -t $DOCKER_ROOT/cassandra-jenkins:latest
    - <<: *docker-build
      script: docker build hugo -t $DOCKER_ROOT/hugo:latest
    - <<: *docker-build
      script: docker build pleroma -t $DOCKER_ROOT/pleroma:latest
    - <<: *docker-build
      script: docker build prosody -t $DOCKER_ROOT/prosody:latest
