language: minimal

services:
  - docker

cache:
  directories:
    "./cache"

jobs:
  include:
    - stage: Setup
      branches:
        only:
          - master
      install:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - stage: Build
      script:
        - minecraft/build.sh
    - stage: Push
      branches:
        only:
          - master
      script:
        - utils/push.sh
