language: shell

services:
  - docker

cache:
  directories:
    "./cache"

jobs:
  include:
    - &docker-build
      stage: Build
      install: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      script: minecraft/build.sh
      after_script: utils/push.sh
    - <<: *docker-build
      script: utils/generic_build.sh cassandra/jenkins cassandra-jenkins weekly
    - <<: *docker-build
      script: utils/generic_build.sh pleroma pleroma weekly
    - <<: *docker-build
      script: utils/generic_build.sh prosody prosody weekly
